[package]
name = "upwell-example-jobs"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[dependencies]
upwell = { path = "../..", features = ["daemon", "jobs", "tooling", "tracing-subscriber"] }
clap.workspace = true
tokio = { workspace = true }
thiserror.workspace = true
tracing.workspace = true
